server:
  port: ${SERVER_PORT:8090}

spring:
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:200MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:200MB}
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ai-rag-knowledge}
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  ai:
    openai:
      base-url: ${SPRING_AI_OPENAI_BASE_URL:https://api.openai.com}
      api-key: ${SPRING_AI_OPENAI_API_KEY:change-me}
      embedding-model: ${SPRING_AI_OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        options:
          num-batch: ${SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_NUM_BATCH:256}
        model: ${SPRING_AI_OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
    rag:
      embed: ${SPRING_AI_RAG_EMBED:nomic-embed-text}


# Redis
redis:
  sdk:
    config:
      host: ${REDIS_SDK_CONFIG_HOST:localhost}
      port: ${REDIS_SDK_CONFIG_PORT:6379}
      pool-size: ${REDIS_SDK_CONFIG_POOL_SIZE:10}
      min-idle-size: ${REDIS_SDK_CONFIG_MIN_IDLE_SIZE:5}
      idle-timeout: ${REDIS_SDK_CONFIG_IDLE_TIMEOUT:30000}
      connect-timeout: ${REDIS_SDK_CONFIG_CONNECT_TIMEOUT:5000}
      retry-attempts: ${REDIS_SDK_CONFIG_RETRY_ATTEMPTS:3}
      retry-interval: ${REDIS_SDK_CONFIG_RETRY_INTERVAL:1000}
      ping-interval: ${REDIS_SDK_CONFIG_PING_INTERVAL:60000}
      keep-alive: ${REDIS_SDK_CONFIG_KEEP_ALIVE:true}

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
